import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { EquipmentResponse } from '@/api/equipments/iEquipmentsServices';
import { equipmentsServices } from '@/api/equipments/implementation/equipmentsServices';
import { laboratoriesServices } from '@/api/laboratories/implementation/laboratoriesServices';
import { projectsServices } from '@/api/projects/implementation/projectsServices';
import { equipmentCategoriesServices } from '@/api/equipmentCategories/implementation/equipmentCategoriesServices';
import { ConfirmModal } from '@/components/ConfirmModal';
import { useAuth } from '@/context/auth/useAuth';

export const EquipmentDetail = () => {
    const { user } = useAuth(); const canManage = user?.profileType === 'professor';
    const { id } = useParams(); const navigate = useNavigate(); const [item, setItem] = useState<EquipmentResponse | null>(null); const [lab, setLab] = useState('-'); const [project, setProject] = useState('-'); const [category, setCategory] = useState('-'); const [source, setSource] = useState('-'); const [fragile, setFragile] = useState(false); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [error, setError] = useState<string | null>(null);
    useEffect(() => { if (!id) return; Promise.all([equipmentsServices.get(Number(id)), laboratoriesServices.list(), projectsServices.list(), equipmentCategoriesServices.list()]).then(([e, l, p, c]) => { if (!e.data) return; setItem(e.data); setLab(l.data?.find(x => x.id === e.data?.laboratoryId)?.name ?? '-'); setProject(p.data?.find(x => x.id === e.data?.projectId)?.name ?? '-'); const cat = c.data?.find(x => x.id === e.data?.equipmentCategoryId); if (cat) { setCategory(cat.description); setSource(cat.powerSource); setFragile(cat.fragile); } }).finally(() => setLoading(false)); }, [id]);
    if (loading) return <div className="text-center text-muted py-5">Carregando...</div>; if (!item) return <div className="text-center text-muted py-5">Equipamento não encontrado. <Link to="/equipments">Voltar</Link></div>;
    const remove = async () => { try { await equipmentsServices.remove(item.id); navigate('/equipments'); } catch { setModal(false); setError('Não foi possível excluir este equipamento. Verifique se existe empréstimo ativo.'); } };
    return <><div className="d-flex justify-content-between align-items-start mb-4"><div><nav><ol className="breadcrumb mb-1 small"><li className="breadcrumb-item"><Link to="/">Início</Link></li><li className="breadcrumb-item"><Link to="/equipments">Equipamentos</Link></li><li className="breadcrumb-item active">{item.name}</li></ol></nav><h4 className="fw-bold mb-0">{item.name}</h4></div>{canManage && <div className="d-flex gap-2"><Link className="btn btn-outline-dark" to={`/equipments/${item.id}/edit`} state={{ equipment: item }}>Editar</Link><button className="btn btn-outline-danger" onClick={() => setModal(true)}>Excluir</button></div>}</div>{error && <div className="alert alert-danger">{error}</div>}
        <div className="row g-4"><div className="col-lg-8"><div className="card"><div className="card-body p-4"><h6 className="fw-semibold mb-4 pb-2 border-bottom">Dados do equipamento</h6><div className="row g-3"><div className="col-12"><p className="text-muted small mb-1">Nome</p><p className="fw-semibold mb-0">{item.name}</p></div><div className="col-md-6"><p className="text-muted small mb-1">Laboratório</p><p className="mb-0">{lab}</p></div><div className="col-md-6"><p className="text-muted small mb-1">Projeto</p><p className="mb-0">{project}</p></div><div className="col-12"><p className="text-muted small mb-1">Categoria</p><p className="mb-0">{category}</p></div></div></div></div></div><div className="col-lg-4"><div className="card"><div className="card-body p-4"><h6 className="fw-semibold mb-4 pb-2 border-bottom">Características</h6><p className="text-muted small mb-1">Fonte de alimentação</p><p>{source}</p><p className="text-muted small mb-1">Manuseio</p><span className={`badge border ${fragile ? 'bg-warning-subtle text-warning-emphasis' : 'bg-light text-secondary'}`}>{fragile ? 'Frágil' : 'Comum'}</span></div></div></div></div>
        <ConfirmModal show={modal} title="Excluir equipamento" message={`Tem certeza que deseja excluir "${item.name}"?`} confirmLabel="Excluir" onConfirm={remove} onCancel={() => setModal(false)} /></>;
};
