import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import type { EquipmentCategoryResponse } from '@/api/equipmentCategories/iEquipmentCategoriesServices';
import { equipmentCategoriesServices } from '@/api/equipmentCategories/implementation/equipmentCategoriesServices';
import { useAuth } from '@/context/auth/useAuth';

export const EquipmentCategoryList = () => {
    const { user } = useAuth(); const canManage = user?.profileType === 'professor';
    const [items, setItems] = useState<EquipmentCategoryResponse[]>([]); const [search, setSearch] = useState(''); const [fragile, setFragile] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
    useEffect(() => { equipmentCategoriesServices.list().then(r => setItems(r.data ?? [])).catch(() => setError('Não foi possível carregar as categorias.')).finally(() => setLoading(false)); }, []);
    const filtered = useMemo(() => items.filter(i => (!search || `${i.description} ${i.powerSource}`.toLowerCase().includes(search.toLowerCase())) && (!fragile || String(i.fragile) === fragile)), [items, search, fragile]);
    return <><div className="d-flex justify-content-between align-items-start mb-4"><div><nav><ol className="breadcrumb mb-1 small"><li className="breadcrumb-item"><Link to="/">Início</Link></li><li className="breadcrumb-item active">Categorias de equipamentos</li></ol></nav><h4 className="fw-bold mb-0">Categorias de equipamentos</h4></div>{canManage && <Link className="btn btn-dark" to="/equipment-categories/new">+ Nova categoria</Link>}</div>
        <div className="card mb-4"><div className="card-body"><div className="row g-3"><div className="col-md-7"><input type="search" className="form-control" placeholder="Buscar por descrição ou fonte..." value={search} onChange={e => setSearch(e.target.value)} /></div><div className="col-md-3"><select className="form-select" value={fragile} onChange={e => setFragile(e.target.value)}><option value="">Todos</option><option value="true">Frágeis</option><option value="false">Não frágeis</option></select></div><div className="col-md-2"><button className="btn btn-outline-secondary w-100" onClick={() => { setSearch(''); setFragile(''); }}>Limpar</button></div></div></div></div>
        <div className="card"><div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead className="table-light"><tr><th>Descrição</th><th>Fonte de alimentação</th><th>Manuseio</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="text-center text-muted py-4">Carregando...</td></tr> : error ? <tr><td colSpan={4} className="text-center text-danger py-4">{error}</td></tr> : filtered.length === 0 ? <tr><td colSpan={4} className="text-center text-muted py-4">Nenhuma categoria encontrada.</td></tr> : filtered.map(i => <tr key={i.id}><td className="fw-semibold">{i.description}</td><td>{i.powerSource}</td><td><span className={`badge border ${i.fragile ? 'bg-warning-subtle text-warning-emphasis' : 'bg-light text-secondary'}`}>{i.fragile ? 'Frágil' : 'Comum'}</span></td><td className="text-end"><Link className="btn btn-sm btn-outline-dark" to={`/equipment-categories/${i.id}`}>Ver</Link></td></tr>)}</tbody></table></div></div>
    </>;
};
