import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import type { EquipmentResponse } from '@/api/equipments/iEquipmentsServices';
import { equipmentsServices } from '@/api/equipments/implementation/equipmentsServices';
import { laboratoriesServices } from '@/api/laboratories/implementation/laboratoriesServices';
import { projectsServices } from '@/api/projects/implementation/projectsServices';
import { equipmentCategoriesServices } from '@/api/equipmentCategories/implementation/equipmentCategoriesServices';
import { useAuth } from '@/context/auth/useAuth';

const PAGE_SIZE = 10;
export const EquipmentList = () => {
    const { user } = useAuth();
    const canManage = user?.profileType === 'professor';
    const [items, setItems] = useState<EquipmentResponse[]>([]); const [labs, setLabs] = useState(new Map<number, string>()); const [projects, setProjects] = useState(new Map<number, string>()); const [categories, setCategories] = useState(new Map<number, string>());
    const [search, setSearch] = useState(''); const [labFilter, setLabFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
    useEffect(() => { Promise.all([equipmentsServices.list(), laboratoriesServices.list(), projectsServices.list(), equipmentCategoriesServices.list()]).then(([e, l, p, c]) => { setItems(e.data ?? []); setLabs(new Map((l.data ?? []).map(x => [x.id, x.name]))); setProjects(new Map((p.data ?? []).map(x => [x.id, x.name]))); setCategories(new Map((c.data ?? []).map(x => [x.id, x.description]))); }).catch(() => setError('Não foi possível carregar os equipamentos.')).finally(() => setLoading(false)); }, []);
    const filtered = useMemo(() => items.filter(i => (!search || `${i.name} ${projects.get(i.projectId) ?? ''}`.toLowerCase().includes(search.toLowerCase())) && (!labFilter || i.laboratoryId === Number(labFilter)) && (!categoryFilter || i.equipmentCategoryId === Number(categoryFilter))).sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')), [items, projects, search, labFilter, categoryFilter]);
    const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const rows = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
    return <><div className="d-flex justify-content-between align-items-start mb-4"><div><nav><ol className="breadcrumb mb-1 small"><li className="breadcrumb-item"><Link to="/">Início</Link></li><li className="breadcrumb-item active">Equipamentos</li></ol></nav><h4 className="fw-bold mb-0">Gerenciamento de equipamentos</h4></div>{canManage && <Link className="btn btn-dark" to="/equipments/new">+ Novo equipamento</Link>}</div>
        <div className="card mb-4"><div className="card-body"><div className="row g-3"><div className="col-lg-5"><input type="search" className="form-control" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Buscar por equipamento ou projeto..." /></div><div className="col-lg-3"><select className="form-select" value={labFilter} onChange={e => { setLabFilter(e.target.value); setPage(1); }}><option value="">Todos os laboratórios</option>{[...labs].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div><div className="col-lg-2"><select className="form-select" value={categoryFilter} onChange={e => { setCategoryFilter(e.target.value); setPage(1); }}><option value="">Todas as categorias</option>{[...categories].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div><div className="col-lg-2"><button className="btn btn-outline-secondary w-100" onClick={() => { setSearch(''); setLabFilter(''); setCategoryFilter(''); setPage(1); }}>Limpar</button></div></div></div></div>
        <div className="card"><div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead className="table-light"><tr><th>Equipamento</th><th>Laboratório</th><th>Projeto</th><th>Categoria</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="text-center text-muted py-4">Carregando...</td></tr> : error ? <tr><td colSpan={5} className="text-center text-danger py-4">{error}</td></tr> : rows.length === 0 ? <tr><td colSpan={5} className="text-center text-muted py-4">Nenhum equipamento encontrado.</td></tr> : rows.map(i => <tr key={i.id}><td className="fw-semibold">{i.name}</td><td>{labs.get(i.laboratoryId) ?? `#${i.laboratoryId}`}</td><td>{projects.get(i.projectId) ?? `#${i.projectId}`}</td><td><span className="badge bg-light text-dark border">{categories.get(i.equipmentCategoryId) ?? `#${i.equipmentCategoryId}`}</span></td><td className="text-end"><Link className="btn btn-sm btn-outline-dark" to={`/equipments/${i.id}`}>Ver</Link></td></tr>)}</tbody></table></div>{pages > 1 && <div className="card-footer bg-white d-flex justify-content-between"><small className="text-muted">{filtered.length} resultado(s)</small><ul className="pagination pagination-sm mb-0">{Array.from({ length: pages }, (_, i) => i + 1).map(p => <li key={p} className={`page-item ${page === p ? 'active' : ''}`}><button className="page-link" onClick={() => setPage(p)}>{p}</button></li>)}</ul></div>}</div>
    </>;
};
